export const buttonStyles = {
    stats: {
        background: "none",
        color: "white",
        marginLeft: "10px",
        padding: "5px",
        cursor: "pointer",
        border: "0.1px solid #6894cc",
        background: "#6894cc",
        borderRadius: "5px",
        textTransform: "uppercase",
        textAlign: "center",
    },
    types: {
        background: "none",
        color: "white",
        marginLeft: "10px",
        padding: "5px",
        cursor: "pointer",
        border: "0.1px solid #6894cc",
        background: "#6894cc",
        borderRadius: "5px",
        textTransform: "uppercase",
        textAlign: "center",
    },
};
